### ISSUE TITLE
TypeError: traitify.onFinished is not a function

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [traitify/traitify-js-widgets#4]
I'm using this bit of code, as mentioned in the readme:
```
<script src="https://cdn.traitify.com/js/widgets/v1.js"></script>
    <script>
        Traitify.setPublicKey("pubkey");
        Traitify.setHost("https://api-sandbox.traitify.com");
        Traitify.setVersion("v1");
        var assessmentId = 'assessment-id';
        var traitify = Traitify.ui.load(assessmentId, ".assessment");
        traitify.onFinished(function() {
            // do stuff
       });
    </script>
```
But it's giving me the error in the title. What am I doing wrong?

**Comment by carsonwright** [comment]
You have to supply an assessment Id right now you're supplying the example data. Use our nodejs, Ruby, go, java, python or php library to create your assessment id

**Comment by carsonwright** [comment]
You have to supply an assessment Id right now you're supplying the example data. Use our nodejs, Ruby, go, java, python or php library to create your assessment id

**Comment by carsonwright** [comment]
Oh also you need to put your actual public key in as well

**Comment by github-account-because-they-want-it** [comment]
Thank you Carson. I use real data in my code, these are just for demonstration. If I should put the real pieces here, please let me know.

**Comment by carsonwright** [comment]
Which backend library are you using to create your assessment id?

**Comment by github-account-because-they-want-it** [comment]
I'm using Python's `requests` library, like that:
```
def get_assessment_id():
    # check the user if student directly from the group because the profile may not be ready
    api_url = "https://api-sandbox.traitify.com/v1/assessments/" if settings.DEBUG \
        else "https://api.traitify.com/v1/assessments/"
    traitify_response = requests.post(api_url, headers={"Content-Type": "application/json"},
                                      auth=(settings.TRAITIFY_SECRET_KEY, ":x"),
                                      data=json.dumps({"deck_id": "career-deck"}))
    return traitify_response.json()["id"]
```
And it works.

**Comment by carsonwright** [comment]
Ok good, now there's one more thing. onFinished is not a method of of the main object returned by the load function


```
Traitify.setPublicKey("8asdf8sda-f98as-df8ads-fadsf"); // Example Public Key
Traitify.setHost("api-sandbox.traitify.com"); // Example host url (Defaults to api.traitify.com)
Traitify.setVersion("v1"); // Example Version
var assessmentId = "34aeraw23-3a43a32-234a34as42"; // Example Assessment id

traitify = Traitify.ui.load(assessmentId, ".slide-deck",{slideDeck: {showResults: false}})
traitify.slideDeck.onFinished(function(){
    alert("Finished")
})
```


I would suggest moving the onFinished to the traitify.slideDeck object

**Comment by github-account-because-they-want-it** [comment]
Ok, will give that a try. Then you probably should update the [events section](https://github.com/traitify/traitify-js-widgets#callbacks-events).

**Comment by carsonwright** [comment]
In the events section the widgets are initialized with the first argument being "slideDeck", if you pass in the name of the widget you want to initialize as the first element it returns only that widget instead of the widget set, so you don't have to call slideDeck.onFinished.

That is an option for you if you are not planning on initializing the results automatically after the slide deck is complete.

```
traitify = Traitify.ui.load(
  "slideDeck", 
  assessmentId, 
  ".slide-deck",
  {slideDeck: {showResults: false}}
)
```

**Comment by carsonwright** [comment]
We have a new version of our js widget set we're working on which handles this part a little differently using riotjs observable on the main object instead.

https://github.com/traitify/widget-tags

**Comment by github-account-because-they-want-it** [comment]
I've used the `slideDeck.onFinished` event but it's being fired before the assessment is done, actually it's fired when it's done loading into the page. How do I know when an assessment was done?

**Comment by carsonwright** [comment]
If the onFinished event is being fired its because all the slides have been played. If it is firing on widget load it is because the assessment id provided has already been completed, make sure that the assessment id being provided is new for every new assessment you want the user to complete otherwise it will trigger the onFinished event every load.

If you would like to see where the onFinished event is triggered for reference there are two places, here (this is the one you are seeing fired on load because the slides have already been played):
https://github.com/traitify/traitify-js-widgets/blob/4988a554d24d340a66ad90456c5352df787a852f/src/ui/master.coffee#L69

And here (this one only fires at the end of the slide deck being played):
https://github.com/traitify/traitify-js-widgets/blob/4988a554d24d340a66ad90456c5352df787a852f/src/widgets/slide-deck/2.0.coffee#L66

**Comment by github-account-because-they-want-it** [comment]
Thank you for your help. I have a better understanding now.

**Comment by carsonwright** [comment]
You can contact me any time at via email: carson AT traitify.com 

Hope this helped, I know there are a number of people who have had trouble with the create a new assessment id per user.

**Comment by github-account-because-they-want-it** [comment]
Thank you. I had some trouble with the assessment ids too. Such functionality probably belongs in the client libraries. I don't know why it's not there.
